alquipiso/alquipiso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from modules.alquileres import views
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('alquileres/', include('modules.alquileres.urls', namespace='alquileres'),),
    path('accounts/', include('django.contrib.auth.urls')),
]

# Serve media files during development (only necessary for dev, not for production)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alquipiso/modules/alquileres/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'alquileres' 
urlpatterns = [
    path('', views.index, name='index'),  # Página de inicio

    # Rutas para Alojamientos
    path('alojamientos/', views.list_alojamientos, name='alojamientos'),  # This should list all alojamientos
    path('propietario/<int:propietario_id>/alojamientos/', views.list_alojamientos_propietario, name='list_alojamientos_propietario'),  # Alojamientos de un propietario específico
    path('create_alojamiento/', views.create_alojamiento, name='create_alojamiento'),
    path('edit_alojamiento/<int:alojamiento_id>/', views.edit_alojamiento, name='edit_alojamiento'),
    path('alojamientos/<int:alojamiento_id>/reservas/', views.list_reservas_alojamiento, name='list_reservas_alojamiento'),
    path('delete_alojamiento/<int:alojamiento_id>/', views.delete_alojamiento, name='delete_alojamiento'),

    path('perfil/', views.user_profile, name='user_profile'),

    # Rutas para Propietarios
    path('propietarios/', views.list_propietarios, name='list_propietarios'),  # Lista de propietarios
    path('propietario/<int:propietario_id>/', views.show_propietario, name='show_propietario'),  # Detalle de propietario

    # Rutas para Clientes
    path('clientes/', views.list_clientes, name='list_clientes'),  # Lista de clientes
    path('cliente/<int:cliente_id>/', views.show_cliente, name='show_cliente'),  # Detalle de cliente

    # Rutas para Reservas
    path('reservas/', views.list_reservas, name='list_reservas'),  # Lista de reservas
    path('reserva/<int:reserva_id>/', views.detalles_reserva, name='detalles_reserva'),  # Detalle de reserva
    path('cliente/<int:cliente_id>/reservas/', views.list_reservas_cliente, name='list_reservas_cliente'),  # Reservas de un cliente específico
    path('alojamiento/<int:alojamiento_id>/reservas/', views.list_reservas_alojamiento, name='list_reservas_alojamiento'),  # Reservas de un alojamiento específico
    path('create_reserva/<int:alojamiento_id>/', views.create_reserva, name='create_reserva'),
    path('detalles_reserva/<int:reserva_id>/', views.detalles_reserva, name='detalles_reserva'),
    path('pagar/<int:reserva_id>/', views.procesar_pago, name='procesar_pago'),
    path('pago-exitoso/', views.pago_exitoso, name='pago_exitoso'),
    path('pago-cancelado/', views.pago_cancelado, name='pago_cancelado'),
    path('webhook/', views.stripe_webhook, name='stripe_webhook'),
    path('cancelar_reserva/<int:reserva_id>/', views.delete_reserva, name='delete_reserva'),
    path('notificaciones/marcar_como_leidas/', views.marcar_notificaciones_como_leidas, name='marcar_notificaciones_como_leidas'),



    path('register/', views.register, name='register'),  # Registro de usuario
    path('login/', views.login_view, name='login'),  # Inicio de sesión
    path('logout/', views.logout_view, name='logout'),  # Cierre de sesión
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alquipiso/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Favicon -->
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />

    <!-- Bootstrap Icons -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous" />

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

    {% block title %}
    <title>Alquipiso</title>
    {% endblock title %}
</head>

<body class = "bg-image"
      style = "background-image: url('https://i.pinimg.com/736x/a8/01/6c/a8016c490fbca1c9dbbc9c1a801db180.jpg')
               height = 100vh">

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">Alquipiso</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto"> <!-- 'ms-auto' class for right-aligned items -->
    
                    {% if user.is_authenticated %}
                    <!-- Icono de campanita -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="notificationDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false" onclick="marcarComoLeidas()">
                            <i class="bi bi-bell"></i>
                            {% if notificaciones_no_leidas %}
                                <span class="badge bg-danger rounded-pill">
                                    {{ notificaciones_no_leidas }}
                                </span>
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="notificationDropdown">
                            {% if notificaciones %}
                                {% for notificacion in notificaciones %}
                                <li>
                                    <a class="dropdown-item {% if notificacion.leido == False %}fw-bold{% endif %}">
                                        {% if notificacion.leido == False %}
                                        <span class="badge bg-danger rounded-circle" style="width: 8px; height: 8px;"></span>
                                        {% endif %}
                                        {{ notificacion.mensaje }}
                                        <small class="text-muted d-block">{{ notificacion.timestamp|timesince }} ago</small>
                                    </a>
                                </li>
                                {% endfor %}
                            {% else %}
                                <li><span class="dropdown-item-text text-muted">No tienes notificaciones</span></li>
                            {% endif %}
                        </ul>
                    </li>
                    
                    {% if user.propietario %} <!-- Check if user has a related Propietario -->
                    <li class="nav-item">
                        <a class="nav-link"
                            href="{% url 'alquileres:list_alojamientos_propietario' propietario_id=user.propietario.id %}">Mis
                            alojamientos</a>
                    </li>
                    {% endif %}
                    {% if user.cliente %} <!-- Check if user has a related Cliente -->
                    <li class="nav-item">
                        <a class="nav-link"
                            href="{% url 'alquileres:list_reservas_cliente' cliente_id=user.cliente.id %}">Mis
                            reservas</a>
                    </li>
                    {% endif %}
    
                    <!-- Logout link -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'alquileres:logout' %}">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'alquileres:user_profile' %}">
                            <i class="fas fa-user-circle" style="font-size: 1.5em;"></i>
                        </a>
                    </li>
                    {% else %}
                    <!-- Login link for unauthenticated users -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'alquileres:login' %}">Registra tu alojamiento</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'alquileres:login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->
    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
    <script>
            function marcarComoLeidas() {
                fetch("{% url 'alquileres:marcar_notificaciones_como_leidas' %}", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                        "X-CSRFToken": "{{ csrf_token }}"
                    },
                    body: JSON.stringify({
                        'user': "{{ user.id }}"
                    })
                })
                .then(response => response.json())
                .then(data => {
                    if (data.status === 'success') {
                        // Si las notificaciones fueron marcadas como leídas, actualizar la UI
                        document.getElementById('notificationDropdown').querySelector('.badge').style.display = 'none';
                    } else {
                        console.log('Error al marcar las notificaciones como leídas: ', data.message);
                    }
                })
                .catch(error => console.error('Error al hacer la solicitud:', error));
            }
    </script>
        
</body>

</html>